### ISSUE TITLE
Go through Slack Checklist for App Directory Submission + Review

### ISSUE THREAD

**Issue by rebekkaorth** [falcowinkler/kudo-box#18]
We need to go through the checklist provided by Slack to make sure we have everything for the review. 

https://app.slack.com/app-settings/T02TTFTFZEK/A02VBT87RAA/submission

 Amongst others we still need to check the following: 
- [ ] Data retention policy
- [ ] Data archival/removal policy
- [ ] Data storage policy
- [ ] Certifications & compliance
- [ ] Terms of Service URL
- [x] Security
